#
#Fri Oct 04 21:24:05 EDT 2024
WhatsNewVersion=v6.0
InitializationVectorDBPassphrase=NlBkRStONDl2cHROdHJua3JUa01id1F0ZVNRTTBESWk5RXJxcGR1QTdpUT0\=
InitialRandomDBPassphrase=true
PrivacyDeliveryReceiptsSet=true
CurrentTheme=SYSTEM
DesktopWindowState={\n    "width"\: 756,\n    "height"\: 944,\n    "x"\: 0,\n    "y"\: 38\n}
EncryptedDBPassphrase=NlBkRStONDl2cHROdHJua3JUa01id1F0ZVNRTTBESWk5RXJxcGR1QTdpUT0\=
NewDatabaseInitialized=true
CurrentThemeIds={}
LastMigratedVersionCode=237
ChatLastStart=1728089717615
ChatStopped=false
OnboardingStage=OnboardingComplete
